name: MSYS2
on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  msys2-mingw64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: mingw32, env: i686 }
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: >-
            git
            mingw-w64-${{matrix.env}}-cc
            mingw-w64-${{matrix.env}}-boost
            mingw-w64-${{matrix.env}}-SDL2
            mingw-w64-${{matrix.env}}-cmake
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          git submodule init
          git submodule update
          cmake -B ${{matrix.env}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build ${{matrix.env}}
